apiVersion: v1
kind: Namespace
metadata:
  name: oom-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom-kill-demo
  namespace: oom-demo
  labels:
    app: oom-kill-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oom-kill-demo
  template:
    metadata:
      labels:
        app: oom-kill-demo
    spec:
      containers:
      - name: oom-kill-demo
        image: 548982503441.dkr.ecr.us-east-1.amazonaws.com/oom-kill-demo:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            # Set a low memory limit to trigger OOMKill quickly
            memory: "128Mi"
            cpu: "200m"
